const {chromium}=require('playwright'),assert=require('node:assert/strict');
const base=process.env.SITE_URL||'http://127.0.0.1:4173';
(async()=>{
 const browser=await chromium.launch();const context=await browser.newContext({viewport:{width:1440,height:1000}});
 await context.route('**/quest-world.js*',r=>r.abort());await context.route('**/quest-avatar.js*',r=>r.abort());
 await context.route('**/quest-cloud-config.js*',r=>r.fulfill({contentType:'text/javascript',body:"export const cloudConfig={url:'https://journey-test.supabase.co',publishableKey:'sb_publishable_test'}"}));
 let online=true,records=[],surveys=[],reads=0;
 await context.route('https://journey-test.supabase.co/**',async r=>{const path=new URL(r.request().url()).pathname;let data={};if(path.includes('signup'))data={access_token:'test',refresh_token:'refresh',expires_in:3600};else if(path.endsWith('quest_board')){reads++;data=[];}else if(path.endsWith('quest_reflection_summary'))data={ready:false};else if(path.endsWith('quest_record')){if(!online)return r.fulfill({status:503,body:'{}',contentType:'application/json'});records.push(r.request().postDataJSON());data={accepted:true,added:true};}else if(path.endsWith('quest_reflect')){if(!online)return r.fulfill({status:503,body:'{}',contentType:'application/json'});surveys.push(r.request().postDataJSON());data={accepted:true};}await r.fulfill({contentType:'application/json',body:JSON.stringify(data)});});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/game.html');await page.locator('#site-tour').waitFor({state:'visible'});
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'test-results/tour-mobile.png'});
 for(let i=0;i<3;i++)await page.locator('#tour-next').click();assert.match(await page.locator('#tour-body').textContent(),/ไม่มีปุ่มอัปโหลดไฟล์โดยตรง/);
 await page.locator('#tour-never').check();await page.locator('#tour-skip').click();await page.reload();assert.equal(await page.locator('#site-tour').isVisible(),false);await page.locator('.tour-launcher').click();assert.equal(await page.locator('#site-tour').isVisible(),true);await page.locator('#tour-skip').click();
 await page.setViewportSize({width:1440,height:1000});await page.waitForFunction(()=>document.querySelector('#member-status').textContent.includes('80'));await page.locator('#student-id').fill('A12');await page.locator('#login-form button[type=submit]').click();assert.equal(await page.locator('#join-ranking').isChecked(),true);
 const round=await page.evaluate(()=>JSON.parse(localStorage.getItem('research10.quest.member.A12')).round);
 assert.equal(await page.locator('.atlas-question').count(),124);await page.locator('#continue-discovery').click();
 for(let i=0;i<124;i++){await page.locator('#challenge').waitFor({state:'visible'});assert.match(await page.locator('#question-topic').textContent(),new RegExp(`ข้อ ${i+1} / 124`));await page.locator('.answer').first().click();await page.locator('#next-discovery').click();if(i%30===29)console.log(`Reached ${i+1} questions`);}
 assert.match(await page.locator('#atlas-progress').textContent(),/124 \/ 124/);assert.equal(await page.locator('.atlas-question.discovered').count(),124);assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('research10.quest.member.A12')).round),round);
 await page.locator('#atlas-state').selectOption('new');assert.equal(await page.locator('.atlas-question').count(),0);await page.locator('#atlas-state').selectOption('all');await page.locator('#question-atlas').screenshot({path:'test-results/atlas-complete.png'});
 online=false;await page.locator('.atlas-question').first().click();await page.locator('.answer').first().click();await page.locator('#finish-question').click();await page.waitForFunction(()=>document.querySelector('#cloud-message').textContent.includes('รอส่ง'));online=true;await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.waitForFunction(()=>document.querySelector('#cloud-message').textContent.includes('ส่งแต้มวันนี้แล้ว'));
 // Preference stays off after sign-in and reload; no repeated consent prompt.
 await page.locator('#join-ranking').uncheck();await page.reload();await page.locator('#student-id').fill('A12');assert.equal(await page.locator('#login-online').isChecked(),false);await page.locator('#login-form button[type=submit]').click();assert.equal(await page.locator('#join-ranking').isChecked(),false);
 await page.locator('#open-survey').click();assert.equal(await page.locator('#share-survey').isChecked(),true);for(let i=0;i<3;i++)await page.locator(`input[name="survey-${i}"][value="4"]`).check();online=false;await page.locator('#survey-form button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#survey-status').textContent.includes('รอส่ง'));
 online=true;await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.waitForFunction(()=>document.querySelector('#survey-status').textContent.includes('ส่งความคิดเห็นแล้ว'));assert.equal(surveys.length,1);assert.equal(surveys[0].p_code,undefined);
 await page.locator('#share-survey').uncheck();await page.locator('#close-survey').click();await page.reload();await page.locator('#student-id').fill('A12');await page.locator('#login-form button[type=submit]').click();await page.locator('#open-survey').click();assert.equal(await page.locator('#share-survey').isChecked(),false);await page.locator('#close-survey').click();
 assert.ok(reads>1);assert.ok(records.length>0);assert.deepEqual(errors,[]);
 for(const route of ['index.html','documents.html','portfolio.html']){await page.goto(base+'/'+route);assert.equal(await page.locator('#site-tour').isVisible(),false);await page.locator('.tour-launcher').click();assert.equal(await page.locator('#site-tour').isVisible(),true);await page.locator('#tour-skip').click();}
 await browser.close();console.log('PASS: first-use tour, mobile/skip/never/replay, all 124 questions reachable in sequence, preserved world round, persistent opt-out, automatic survey retry, all-page help.');
})().catch(e=>{console.error(e);process.exit(1)});
