const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const out = path.join(root, 'test-results');
fs.mkdirSync(out, {recursive:true});
(async () => {
 const browser = await chromium.launch({headless:true});
 const context = await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});
 const page = await context.newPage();
 const errors = [];
 const count = async (selector,n) => page.waitForFunction(({selector,n})=>document.querySelectorAll(selector).length===n,{selector,n});
 page.on('pageerror',error => errors.push(error.message));
 await page.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'});
 await page.screenshot({path:out+'/home-desktop.png'});
 await count('h1',1);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.getByRole('button',{name:'หยุดโมชัน'}).click();
 assert.equal(await page.locator('.orbital-scene').evaluate(e=>e.classList.contains('motion-paused')),true);
 await page.locator('#explore').scrollIntoViewIfNeeded();
 await page.waitForTimeout(800);
 await page.screenshot({path:out+'/home-resources.png'});
 await page.goto('http://127.0.0.1:4173/portfolio.html',{waitUntil:'networkidle'});
 await page.waitForSelector('.track-card');
 await page.screenshot({path:out+'/portfolio-desktop.png',fullPage:true});
 await count('.track-card',2);
 await count('.member-card',0);
 await page.locator('.track-card[href="#Advanced"]').click();
 await count('.group-card',6);
 await page.locator('.group-card[href="#Advanced/3"]').click();
 await count('.member-card',5);
 await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));
 await page.screenshot({path:out+'/members-desktop.png',fullPage:true});
 const data=JSON.parse(fs.readFileSync(root+'/researchers.json','utf8'));
 assert.equal(data.length,80); assert.equal(new Set(data.map(m=>m.folderUrl)).size,80);
 const correctedNames={B07:'ภญ.มธุรินทร์ วงศ์โยธา',B08:'ภญ.ขัตติยา บุญรอง',B11:'นางสาวศุภารัตน์ พิลาลัย',B24:'ภญ.ปริศนา วงศ์ผาคุณ',B34:'ภก.วิรัตน์ พวงจันทร์',B50:'ภญ.วลัยพร แปลงมาลย์'};
 for (const [code,name] of Object.entries(correctedNames)) assert.equal(data.find(m=>m.code===code).name,name,`confirmed name ${code}`);
 for(const track of ['Advanced','Basic']){
  for(let group=1;group<=(track==='Advanced'?6:10);group++){
   await page.goto('http://127.0.0.1:4173/portfolio.html#'+track+'/'+group);
   await page.waitForFunction(()=>document.querySelector('.member-card')&&document.querySelector('#portfolio-app').getAttribute('aria-busy')==='false');
   const actual=await page.locator('.member-card').evaluateAll(els=>els.map(el=>({url:el.href,code:el.querySelector('.member-code b').textContent})));
   const expected=data.filter(m=>m.track===track&&m.group===group);
   await page.locator('.member-photo img').evaluateAll(async imgs=>{for(const img of imgs){img.loading='eager';await img.decode();if(!img.naturalWidth)throw Error('Broken portrait');}});
   assert.deepEqual(actual,expected.map(m=>({url:m.folderUrl,code:m.code})));
   for(const m of expected){
    assert(fs.existsSync(root+'/'+m.image),'Original missing '+m.code);
    assert(fs.existsSync(root+'/assets/portraits/'+m.code+'.webp'),'Portrait missing '+m.code);
    assert(fs.existsSync(root+'/assets/portraits/'+m.code+'-thumb.webp'),'Thumbnail missing '+m.code);
   }
  }
 }
 await page.goto('http://127.0.0.1:4173/portfolio.html');
 await page.waitForSelector('#member-search');
 await page.locator('#member-search').fill('ฐิติภูมิ');
 await count('.member-card',1);
 assert.equal(await page.locator('.member-code b').textContent(),'A12');
 await page.locator('#member-search').fill('B11');
 await count('.member-card',1);
 assert.equal(await page.locator('.member-code b').textContent(),'B11');
 await page.locator('#member-search').fill('no-such-researcher');
 await count('.member-card',0);
 await page.getByRole('button',{name:'ล้างคำค้นหา'}).click();
 await count('.track-card',2);
 await page.locator('.track-card[href="#Basic"]').click();
 await page.locator('.group-card[href="#Basic/2"]').click();
 await count('.member-card',5);
 await page.goBack();
 await count('.group-card',10);
 await page.goBack();
 await count('.track-card',2);
 await page.goto('http://127.0.0.1:4173/portfolio.html#Invalid/999');
 await page.waitForSelector('.track-card');
 await count('.track-card',2);
 await page.route('**/researchers.json',route=>route.fulfill({status:503,body:'unavailable'}));
 await page.reload();
 await page.waitForSelector('#retry-load');
 await page.unroute('**/researchers.json');
 await page.locator('#retry-load').click();
 await page.waitForSelector('.track-card');
 await page.setViewportSize({width:390,height:844});
 await page.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'});
 await page.screenshot({path:out+'/home-mobile.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.locator('.menu-toggle').click();
 assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'true');
 await page.locator('#primary-nav a[href="portfolio.html"]').click();
 await page.waitForSelector('.track-card');
 await page.screenshot({path:out+'/portfolio-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.locator('.track-card[href="#Basic"]').click();
 await page.locator('.group-card[href="#Basic/2"]').click();
 await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));
 await page.screenshot({path:out+'/members-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.goto('http://127.0.0.1:4173/');
 assert.equal(await page.locator('.orbit-one').evaluate(e=>getComputedStyle(e).animationName),'none');
 assert.equal(await page.locator('.motion-control').isVisible(),false);
 await page.goto('http://127.0.0.1:4173/documents.html#videos');
 await count('#videos',1);
 assert.deepEqual(errors,[]);
 await browser.close();
 console.log('PASS: 80 unique folder links; all 16 groups; image files; search; exclusions; history; invalid route; fetch failure/retry; desktop/mobile; menu; reduced motion; video anchor; no JS errors.');
})().catch(e=>{console.error(e);process.exit(1)});
